AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Resume visitor counter backend

Resources:
  VisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: resumeVisitorCounter
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Policies:
        - DynamoDBCrudPolicy:
            TableName: visitor_count
      Events:
        GetCount:
          Type: HttpApi
          Properties:
            Path: /count
            Method: GET

  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitor_count
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
